In [2]:
# Import the necessary libraries

#libraries for data wrangling
import pandas as pd
import numpy as np

#libraries for visualization
import matplotlib.pyplot as plt
import seaborn as sns

#libraries for time
from datetime import datetime, timedelta

#ignore warnings
import warnings
warnings.filterwarnings('ignore')

#set up views
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [3]:
# Load  the data
data_path = r"archive.zip" # I am using relative path
df = pd.read_csv(data_path, low_memory=True,compression='zip') # This is how to load zipped csv file
df.tail()

               ID Case Number                    Date                Block  IUCR        Primary Type                    Description             Location Description  Arrest  Domestic  Beat  District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year              Updated On   Latitude  Longitude                       Location
7784659  12847575    JF420478  09/01/2022 05:00:00 AM      005XX W SURF ST  2825       OTHER OFFENSE        HARASSMENT BY TELEPHONE                        RESIDENCE   False      True  1934      19.0  44.0             6.0       26     1172497.0     1919410.0  2022  01/03/2023 03:46:28 PM  41.934305 -87.641485  (41.934304581, -87.641484982)
7784660  12847801    JF420319  07/08/2022 12:00:00 AM  114XX S PRAIRIE AVE  1130  DECEPTIVE PRACTICE       FRAUD OR CONFIDENCE GAME                           STREET   False     False   531       5.0   9.0            49.0       11     1179966.0     1828818.0  2022  01/03/2023 03:46:28 PM  41.685544 -87.616813  (41.685543881, -87.616812541)
7784661  12847324    JF420102  09/27/2022 11:00:00 AM      023XX E 70TH ST  0810               THEFT                      OVER $500                        RESIDENCE   False     False   331       3.0   5.0            43.0       06     1193181.0     1859005.0  2022  01/03/2023 03:46:28 PM  41.768068 -87.567453  (41.768068052, -87.567452932)
7784662  12847570    JF420427  09/03/2022 10:25:00 AM   052XX W CARMEN AVE  2021           NARCOTICS         POSSESS - BARBITURATES  RESIDENCE - YARD (FRONT / BACK)    True     False  1623      16.0  45.0            11.0       18     1140553.0     1933418.0  2022  01/03/2023 03:46:28 PM  41.973391 -87.758535  (41.973391184, -87.758534512)
7784663  12840464    JF411839  09/26/2022 07:20:00 PM    0000X N MASON AVE  143A   WEAPONS VIOLATION  UNLAWFUL POSSESSION - HANDGUN                         SIDEWALK    True     False  1513      15.0  29.0            25.0       15     1136773.0     1899652.0  2022  01/03/2023 03:46:28 PM  41.880802 -87.773246  (41.880802263, -87.773245737)

In [ ]:
# df=pd.read_csv('Crimes_-_2001_to_Present.csv')

In [6]:
data = {'data':'ada','age':23,'ethnicity': 'Yoruba'}
pd.Series(data)

data            ada
age              23
ethnicity    Yoruba
dtype: object

In [ ]:
df.shape

(7784664, 22)

In [7]:
df.head()

         ID Case Number                    Date                  Block  IUCR Primary Type              Description Location Description  Arrest  Domestic  Beat  District  Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year              Updated On   Latitude  Longitude                       Location
0  10224738    HY411648  09/05/2015 01:30:00 PM        043XX S WOOD ST  0486      BATTERY  DOMESTIC BATTERY SIMPLE            RESIDENCE   False      True   924       9.0  12.0            61.0      08B     1165074.0     1875917.0  2015  02/10/2018 03:50:01 PM  41.815117 -87.670000  (41.815117282, -87.669999562)
1  10224739    HY411615  09/04/2015 11:30:00 AM    008XX N CENTRAL AVE  0870        THEFT           POCKET-PICKING              CTA BUS   False     False  1511      15.0  29.0            25.0       06     1138875.0     1904869.0  2015  02/10/2018 03:50:01 PM  41.895080 -87.765400  (41.895080471, -87.765400451)
2  11646166    JC213529  09/01/2018 12:01:00 AM  082XX S INGLESIDE AVE  0810        THEFT                OVER $500            RESIDENCE   False      True   631       6.0   8.0            44.0       06           NaN           NaN  2018  04/06/2019 04:04:43 PM        NaN        NaN                            NaN
3  10224740    HY411595  09/05/2015 12:45:00 PM      035XX W BARRY AVE  2023    NARCOTICS    POSS: HEROIN(BRN/TAN)             SIDEWALK    True     False  1412      14.0  35.0            21.0       18     1152037.0     1920384.0  2015  02/10/2018 03:50:01 PM  41.937406 -87.716650  (41.937405765, -87.716649687)
4  10224741    HY411610  09/05/2015 01:00:00 PM    0000X N LARAMIE AVE  0560      ASSAULT                   SIMPLE            APARTMENT   False      True  1522      15.0  28.0            25.0      08A     1141706.0     1900086.0  2015  02/10/2018 03:50:01 PM  41.881903 -87.755121  (41.881903443, -87.755121152)

it has 7784664 rows and 22 columns

In [8]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type', 'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate', 'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude', 'Location'], dtype='object')

In [19]:
list(df.columns)

['ID',
 'Case Number',
 'Date',
 'Block',
 'IUCR',
 'Primary Type',
 'Description',
 'Location Description',
 'Arrest',
 'Domestic',
 'Beat',
 'District',
 'Ward',
 'Community Area',
 'FBI Code',
 'X Coordinate',
 'Y Coordinate',
 'Year',
 'Updated On',
 'Latitude',
 'Longitude',
 'Location']

Checking how many unique values we have in each columns

In [18]:
print('Column Name \t\t\t\t\t number of unique rows')
for i in list(df.columns):
    unirow=df[i].nunique()
    print(f'{i}\t\t\t\t\t {unirow}')

Column Name 					 number of unique rows
ID					 7784664
Case Number					 7784121
Date					 3207478
Block					 62845
IUCR					 404
Primary Type					 36
Description					 544
Location Description					 215
Arrest					 2
Domestic					 2
Beat					 304
District					 24
Ward					 50
Community Area					 78
FBI Code					 26
X Coordinate					 79017
Y Coordinate					 130184
Year					 23
Updated On					 5561
Latitude					 889260
Longitude					 888670
Location					 890516

i want to know more about the icur and blocks ,primary type,year,fbi code,community areA, an all other columns where unique number of rows is < 200 000

In [ ]:
for i in list(df.columns):
    if df[i].nunique() <= 200000 :
        print('===================================')
        print(f'    =====Unique {i} ====='.center(100))
        print('===================================')

        unirowhead=df[df[i].unique()].head(7)
        unirowtail=df[df[i].unique()].tail(7)
        print(f'{i}\t\t\t\t\t {unirow}')

===================================
                                        =====Unique Block =====
===================================

AttributeError: 'numpy.ndarray' object has no attribute 'head'